# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: objective-c

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -project DelayedJob.xcodeproj -scheme DelayedJob-Package -sdk macosx ONLY_ACTIVE_ARCH=NO | xcpretty
