#if !canImport(ObjectiveC)
import XCTest

extension DelayedJobTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DelayedJobTests = [
        ("testDoNotRunBeforeDelay", testDoNotRunBeforeDelay),
        ("testRunAfterDelay", testRunAfterDelay),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DelayedJobTests.__allTests__DelayedJobTests),
    ]
}
#endif
